app:
  name: project
  port: 8080

database:
  host: localhost
  port: 5432
  username: ""
  password: ""
  database: ""
cache:
  host: localhost
  port: 6379
  database: 0
logstash:
  host: localhost
  port: 5043